src/dewil/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('questions.urls', namespace='question', app_name='question')),
    url(r'^', include('login.urls', namespace='login', app_name='login')),
]

src/login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^settings/$', views.settings, name='settings'),
]

src/questions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^popular/$', views.popular, name='popular'),
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^answers/$', views.answer, name='answer'),
    url(r'search/', views.search, name='search'),
    url(r'tagsearch/', views.tag_search, name='tag_search'),
    url(r'^$', views.index, name='index'),
]

src/login/models.py
from django.db import models


class User(models.Model):
    img = models.FilePathField()
    login = models.CharField(max_length=30, primary_key=True)
    password = models.IntegerField()

src/questions/models.py
from django.db import models
from login.models import User


class Tag(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30)


class Question(models.Model):
    id = models.IntegerField(primary_key=True)
    #tags = models.ManyToManyField(Tag, verbose_name="question tags")
    desc = models.CharField(max_length=300)
    popularity = models.IntegerField()
    title = models.CharField(max_length=100)
    ans_cnt = models.IntegerField()
    user = models.ForeignKey(User)


class Answer(models.Model):
    pass

src/login/views.py
from django.shortcuts import render_to_response


def login(request):
    return render_to_response('login.html')


def registration(request):
    return render_to_response('registration.html')

def settings(request):
    return render_to_response('settings.html')

src/questions/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import loader
from questions.models import *

tags = [Tag(), Tag()]
tags[0].name = 'bender'
tags[1].name = 'black-jack'
usr = User()
usr.img = '/static/logo200.jpg'
usr.name = 'Bender'
question = Question()
question.id = 1
question.tags = tags
question.short_desc = 'Guys, I have trouble with a moon park. Can\'t find the black-jack...'
question.popularity = 7
question.title = 'How to build a moon park?'
question.ans_cnt = 10
question.user = usr
question.desc = 'Guys, I have trouble with a moon park. Can\'t find the black-jack... Guys, I have trouble with a moon park. Can\'t find the black-jack...'
question.ref = '/answers/'

answers = Answer()
answers.user = usr
answers.popularity = 7
answers.text = 'I don\'t know! :('


def index(request):
    rend_params = {'is_new': True, 'questions': [question] * 10, 'popular_tags': [tags[0]] * 6,
                   'popular_members': [usr] * 5, 'is_short': True}
    template = loader.get_template('questions.html')
    return HttpResponse(template.render(rend_params))


def popular(request):
    rend_params = {'is_new': False, 'questions': [question] * 10}
    template = loader.get_template('questions.html')
    return HttpResponse(template.render(rend_params))


def ask(request):
    return render_to_response('ask.html')


def answer(request):
    rend_params = {'question': question, 'answers': [answers] * 10}
    return render_to_response('answer.html', rend_params)


def search(request):
    return render_to_response('search.html')


def tag_search(request):
    return render_to_response('tag_search.html')

src/templates/answer.html
{% extends 'base.html' %}
{% block right %}
    <br>
    {% include 'question_form.html' %}
    <hr>
    <h2>Answers:</h2>
    {% for answer in answers %}
        {% include 'answer_form.html' %}
    {% endfor %}
    <hr>
    <div style="margin-bottom: 20px; margin-top:20px;">
        <div style="margin-top: 20px;margin-bottom: 20px;">
            <textarea id="wmd-input" class="wmd-input processed" data-min-length=""
                      placeholder="Enter your answer here"
                      tabindex="101" rows="5"
                      cols="80" name="post-text"></textarea>
        </div>
        <button type="button" class="btn btn-success btn-md">Answer</button>

    </div>
{% endblock %}

src/templates/answer_form.html
<div class="answerForm">
    <div class="row">
        <div class="col-md-2">
            <img src="{{ answer.user.img }}">
            <p></p>
            <button type="button" class="btn btn-default">-</button>
            <span>{{ answer.popularity }}</span>
            <button type="button" class="btn btn-default">+</button>
        </div>
        <div class="col-md-10">
            <div class="inForm">
                <p class="lead" style="padding-top: 20px">{{ answer.text }}</p>
                <form style="padding-bottom: 15px;">
                    <label>
                        <input type="checkbox"> Correct!
                    </label>
                </form>
            </div>
        </div>
    </div>
</div>

src/templates/ask.html
{% extends 'base.html' %}
{% block right %}
    <h1>Ask Question</h1>
    <div style="margin-top:20px; margin-bottom: 20px; ">
        <label for="title" style="margin-right: 6px">
            Title
        </label>
        <input id="title" type="text" data-max-length="150" data-min-length="15"
               placeholder="Your question" tabindex="100"
               maxlength="300" name="title" autocomplete="off" style="width: 300px;">
    </div>
    <div style="margin-top: 20px;margin-bottom: 20px;">
        <label for="wmd-input" style="float: left; margin-right: 9px">
            Text
        </label>
        <textarea id="wmd-input" class="wmd-input processed" data-min-length="" tabindex="101" rows="15"
                  cols="80" name="post-text"></textarea>
    </div>
    <div style="margin-top: 20px; margin-bottom: 20px;">
        <label for="tag">
            Тags
        </label>
        <input id="tag" type="text" data-max-length="150" data-min-length="15"
               placeholder="moon, park, puzzle" tabindex="100"
               maxlength="300" name="title" autocomplete="off" style="width: 300px;">
    </div>
    <div>
        <button type="button" class="btn btn-success btn-md">Ask Question</button>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>AskDewil</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap-tag-cloud.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/custom.css" %}">
    <script src="{% static "bootstrap/js/jquery-1.11.3.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tag-cloud.js" %}"></script>
</head>
<body>
<!-- Head -->
    <nav class="navbar navbar-inverse"><!-- page content end -->
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">AskDewil</a>
            </div>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" style="border-radius: 15px;">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <div class="navbar-btn navbar-left">
                <button type="submit" class="btn btn-default" id="ask-btn">ASK!</button>
            </div>
            <script type="text/javascript">
                document.getElementById("ask-btn").onclick = function () {
                    location.href = "{% url 'question:ask' %}";
                };
            </script>
            <div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <button id="usr-btn"><img src="{% static 'logo200.jpg' %}" class="img-rounded" style="height: 45px; width:45px;"></button>
                        </li>
                        <script type="text/javascript">
                                document.getElementById("usr-btn").onclick = function () {
                                location.href = "{% url 'login:settings' %}";
                            };
                        </script>
                        <li><a href="#TODO"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login:registration' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="{% url 'login:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<!-- head end -->

<!-- page content -->
<div class="container">
    <div class="row">
        <div class="col-md-8">
            {% block right %}
            {% endblock %}
        </div>
        <div class="col-md-4">
            <h1>Popular Tags</h1>
            <ul id="tag-cloud">
                {% for tag in popular_tags %}
                    <li class="tag-cloud">{{ tag.name }}</li>
                {% endfor %}
            </ul>
            <h1>Popular Members</h1>
            {% for member in popular_members%}
                <p><a class="members">{{ member.name }}</a></p>
            {% endfor %}
        </div>
    </div>
</div>
<!-- page content end -->

<!-- footer -->
<footer class="footer">
    <div class="container">
        <p class="text-muted">(c) 2015</p>
    </div>
</footer>
<!-- footer end -->
</body>
</html>

src/templates/login.html
{% extends 'base.html' %}
{% block right %}
    <h1>Log In</h1>
    <br>
    <form action="#TODO" method="POST">
        <fieldset>
            <div class="row">
                <div class="col-sm-12 col-md-10 ">
                    <div class="form-group">
                        <label>Login:</label>
                        <div class="input-group"> <span class="input-group-addon"> <i class="glyphicon glyphicon-user"></i> </span>
                            <input class="form-control" placeholder="Username" name="loginname" type="text"
                                   autofocus style="width: 300px;" data-min-length="8"  maxlength="300"
                                   data-max-length="150">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Password:</label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="glyphicon glyphicon-lock"></i> </span>
                            <input class="form-control" placeholder="Password" name="password" type="password" value=""
                                   style="width: 300px;">
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Log In">
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
    <br><br>
    <a href="#">create new account</a>
    <br><br><br><br><br>
{% endblock %}

src/templates/pagination.html
{% block pagination %}
<nav>
    <ul class="pagination">
        {% for page in pagination.page_range %}
            {% if page.number == pagingation.cur_number %}
                <li class="active"><a href="{{ pagination.base_url }}{{ page.number }}">{{ page.number }}<span class="sr-only">(current)</span></a></li>
            {% else %}
                <li class="active"><a href="{{ pagination.base_url }}{{ page.number }}">{{ page.number }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock %}

src/templates/question_form.html
<div class="questionForm">
    <div class="row">
        <div class="col-md-2">
            <img src="{{ question.user.img }}">
            <p></p>
            <button type="button" class="btn btn-default">-</button>
            <span>{{ question.popularity }}</span>
            <button type="button" class="btn btn-default">+</button>
        </div>
        <div class="col-md-10">
            <div class="inForm">
                <h2><a href="{{ question.ref }}">{{ question.title }}</a></h2>
                <p class="lead">
                    {% if is_short %}
                        {{ question.short_desc }}
                    {% else %}
                        {{ question.desc }}
                    {% endif %}
                </p>
                {% if is_short %}
                    <a href="{{ question.ref_ans }}"><u>answer ({{ question.ans_cnt }})</u></a>
                {% endif %}
                Tags:
                {% for tag in question.tags %}
                    <a href="{{ tag.ref }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

src/templates/questions.html
{% extends "base.html" %}

{% block right %}
    <div class="row">
        {% if is_new %}
            <div class="col-md-5">
                <h1>New Questions</h1>
            </div>
            <div class="col-md-5">
                <h3><a href="{% url 'question:popular' %}">Hot Questions</a></h3>
            </div>
        {% else %}
            <div class="col-md-5">
                <h3><a href="{% url 'question:index' %}">New Questions</a></h3>
            </div>
            <div class="col-md-5">
                <h1>Hot Questions</h1>
            </div>
        {% endif %}
        <div class="col-md-2">
        </div>
    </div>
    {% for question in questions %}
        {% include "question_form.html" %}
    {% endfor %}
    {% include "pagination.html" %}

{% endblock %}

src/templates/registration.html
{% extends 'base.html' %}
{% block right %}
    <div style="position: relative;">
        <h1>Registration:</h1>
        <form action="#TODO" method="POST">
            <fieldset>
                <div class="row">
                    <div class="col-sm-12 col-md-10 ">
                        <div class="form-group">
                            <label>Login:</label>
                            <div class="input-group"> <span class="input-group-addon"> <i class="glyphicon glyphicon-user"></i> </span>
                                <input class="form-control" placeholder="Username" name="loginname" type="text"
                                       autofocus style="width: 300px;" data-min-length="8"  maxlength="300"
                                       data-max-length="150">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Email:</label>
                            <div class="input-group"> <span class="input-group-addon" id="basic-addon1">@</span>
                                <input class="form-control" placeholder="Email" name="email" type="text"
                                       autofocus style="width: 300px;" data-min-length="8"  maxlength="300"
                                       data-max-length="150">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>NickName :</label>
                            <div class="input-group"> <span class="input-group-addon"> <i class="glyphicon glyphicon-sunglasses"></i> </span>
                                <input class="form-control" placeholder="Your nickname" name="nickname" type="text"
                                       autofocus style="width: 300px;" data-min-length="8"  maxlength="300"
                                       data-max-length="150">
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Password:</label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="glyphicon glyphicon-lock"></i> </span>
                                <input class="form-control" placeholder="Password" name="password" type="password" value=""
                                       style="width: 300px;">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Repeat password:</label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="glyphicon glyphicon-lock"></i> </span>
                                <input class="form-control" placeholder="Repeat password" name="repeat-password" type="password" value=""
                                       style="width: 300px;">
                            </div>
                        </div>

                        <label for="UploadAvatar">Upload avatar</label>
                        <br>
                        <img id="UploadAvatar" src="{{ user.img }}" style="width: 20%;">
                        <br>
                        <input type="file" name="pic" width="80px"/>
                        <br>
                        <div>
                            <button type="button" class="btn btn-success btn-md">Save</button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

src/templates/search.html
{% extends 'base.html' %}
{% block right %}
    <div style="margin-bottom: 20px;">
        <h1><b>Search:</b> {{ query }}</h1>
        <input type="text" class="form-control" placeholder="Search...">
    </div>
    {% for question in questions %}
        {% include 'question_form.html' %}
    {% endfor %}
    {% include 'pagination.html' %}
{% endblock %}

src/templates/settings.html
{% extends 'base.html' %}
{% block right %}
    <div style="position: relative;">
        <h1>Settings: {{ user.name }}</h1>
        <form action="#TODO" method="POST">
            <label for="login">Login</label>
            <br>
            <input id="login" placeholder="{{ user.login }}" type="text" data-max-length="150"
                   data-min-length="8"
                   tabindex="100"
                   maxlength="300" style="width: 300px;">
            <br>
            <label for="Email">Email</label>
            <br>
            <input id="Email" placeholder="{{ user.email }}" type="text" data-max-length="150"
                   tabindex="100"
                   maxlength="300" style="width: 300px;">
            <label for="NickName">NickName</label>
            <br>
            <input id="NickName" type="text" placeholder="{{ user.name }}" data-max-length="150" data-min-length="15"
                   tabindex="100"
                   maxlength="300" style="width: 300px;">
            <label for="UploadAvatar">Upload avatar</label>
            <br>
            <img id="UploadAvatar" src="{{ user.img }}" style="width: 20%;">
            <br>
            <input type="text" placeholder="C:/src/images/" width="80px"/>
            <button type="button" class="btn btn-success">Choose</button>

            <div>
                <button type="button" class="btn btn-success btn-md">Save</button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/tag_search.html
{% extends 'base.html' %}
{% block right %}
    <div style="margin-bottom: 20px;">
        <h1><b>Tag:</b> {{ tag }}</h1>
        <input type="text" class="form-control" placeholder="Search...">
    </div>
    {% for question in questions %}
        {% include 'question_form.html' %}
    {% endfor %}
    {% include 'pagination.html' %}
{% endblock %}